plugins:
  - jekyll-relative-links
relative_links:
  enabled: true
  collections: true
include:
  - README.md
  - index.md

sass:
  sass_dir: scss

collections:
  - staff_members

  collections_dir: my_collections