plugins:
  - jekyll-relative-links
relative_links:
  enabled: true
  collections: true
  collections_dir: my_collections
include:
  - README.md
  - index.md

sass:
  sass_dir: scss

collections:
  staff_members:
    output: true
    permalink: /:collection/:name
  books:
    output: true
    permalink: /:collection/:title
  