plugins:
  - jekyll-relative-links
relative_links:
  enabled: true
  collections: true
include:
  - README.md
  - index.md
  - trash.html

sass:
  sass_dir: scss

collections:
  staff_members:
    output: true 
  collections_dir: 
    my_collections